name: yarn-build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: nodejs environment
      uses: actions/setup-node@v2.1.2
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build